### ISSUE TITLE
Error in xj[i] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by krcarriere** [jacob-long/interactions#19]
I tried replicating this in example data with no luck. So, clearly my data is acting funky that the example survey data does not. 

```r
datamod2 <- read.csv("interactionsdata.csv")
#datamod2<- datamod2[complete.cases(datamod2), ] Desperate ideas, no difference.
library(survey)
library(interactions)
anes_design_mod2 <-
  svydesign( 
    ~psu , 
    strata = ~strata, 
    data = datamod2, 
    weights = ~weight, 
    nest = TRUE 
  )

#Try it both with binomial 
model6 <- svyglm(wiretapnowarrant ~ tthreat.c*poliknow.c*auth.both.t.c +
                          republican + independent + male + age.c + rfinc + education + race + muslim_thermo.c,
                        family="binomial",
                        na.action=na.omit, 
                        anes_design_mod2)
#And quasi-binomial
model6b <- svyglm(wiretapnowarrant ~ tthreat.c*poliknow.c*auth.both.t.c +
                            republican + independent + male + age.c + rfinc + education + race + muslim_thermo.c,
                          family="quasibinomial", 
                          na.action=na.omit,
                          anes_design_mod2)

summ(model6)
sim_slopes(model6, pred = tthreat.c, modx = poliknow.c, mod2 = auth.both.t.c)
typeof(datamod2$tthreat.c)
typeof(datamod2$poliknow.c)
typeof(datamod2$auth.both.t.c)
sim_slopes(model6b, pred = tthreat.c, modx = poliknow.c, mod2 = auth.both.t.c)
```
Can't upload the data via github so a dropbox link for it provided here: 
https://www.dropbox.com/s/xvjn1xdwmyy6b94/interactionsdata.csv?dl=0

**Comment by jacob-long** [comment]
Hi Kevin, thanks for sharing enough info to let me try to replicate this. Unfortunately (or maybe fortunately), I do not get an error on my machine. That makes me wonder about versioning, since there's a bugfix I released about a day after you posted this that might be related. There's another bugfix I uploaded to Github yesterday that might be related to this, too.

Could you update the `interactions` package and let me know if that fixes it? If it doesn't, I'd want you to try it with the Github version of the package to see if that fixes it too:

```r
devtools::install_github("jacob-long/interactions")
```
