### ISSUE TITLE
Re-Label Axis and data points in Johnson-Neyman Plot

### ISSUE THREAD

**Issue by Klesa27** [jacob-long/interactions#21]
Hello,
I'm attempting to re-label the axes for a plot I made in R studio, but am having some trouble figuring out exactly how to do so. Apologies if this is in the packages section of R, and I just missed it. I'm still somewhat new to R.

I used the following code to create my plot:
johnson_neyman(model, pred, modx, vmat = NULL, alpha = 0.05,
  plot = TRUE, control.fdr = FALSE, line.thickness = 0.5,
  df = "residual", digits = getOption("jtools-digits", 2),
  critical.t = NULL, sig.color = "black", insig.color = "grey",
  mod.range = NULL, title = "Johnson-Neyman plot")

But I would like to know if there's an easy way to re-labeling my predictor variable and modx variable as I was hoping to use these plots in the paper I'm submitting for publication.

Additionally, my modx variable is children's age - centered. So I was wondering if there's a way to also re-label those numbers so they don't show up as -1, 0, 1, etc. but as the actual ages they represent.

Many thanks for any help you're able to offer!

**Comment by jacob-long** [comment]
Hi! I've transferred this issue to the new `interactions` package, where this function has moved. 

As for your questions, it is possible to accomplish this using `ggplot2`, which is the package this function relies on to create the plot. Many people who are new (and often not so new) to R run into issues with `ggplot2`, so don't feel bad. I made the package because I know it can be hard to learn all this stuff!

I'll use some example code to show how to accomplish this. First, the axis titles should be fairly simple, using the `ggplot2` functions `xlab()` and `ylab()`.

```r
library(interactions)
library(ggplot2)
states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy, data = states)
object <- johnson_neyman(model = fit, pred = Murder, modx = Illiteracy)
# the plot is stored in object$plot
object$plot + xlab("My new x-axis title") + ylab("My new y-axis title")
```

Relabeling the points along the x-axis is a little more complex, but doable. It will require you to know the mean of the variable on the x-axis because we're going to add that number to the existing labels. For demonstration purposes, we'll say the mean is 5. We make a function that adds the mean to its input and then give that to `ggplot2`'s `scale_x_continuous()` function to the `labels` argument, telling it to apply that function to all the values on the x-axis.

```r
# Creating a function that will edit the labels
new_labeller <- function(x) x + 5 # adds 5 
# still using the object from earlier
object$plot + scale_x_continuous(labels = new_labeller)
```

Putting those pieces together, then...

```r
library(interactions)
library(ggplot2)
states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy, data = states)
object <- johnson_neyman(model = fit, pred = Murder, modx = Illiteracy)
# Creating a function that will edit the labels
new_labeller <- function(x) x + 5 # adds 5 
# the plot is stored in object$plot
object$plot + xlab("My new x-axis title") + ylab("My new y-axis title") +
  scale_x_continuous(labels = new_labeller)
```

**Comment by Mababyak** [comment]
Thanks so much for this, Jacob! Been trying to figure this out for some time! Maybe you can include this info on the vignettes page? 

Really appreciate the package!

**Comment by zaslove** [comment]
Thanks! I too have been trying to figure this out. But this works!
