### ISSUE TITLE
Order of output table from sim_slopes() with categorical moderator.

### ISSUE THREAD

**Issue by MichaelJMahometa** [jacob-long/interactions#55]
When running an interaction model with a quantitative and categorical term---with a categorical moderator---I will factor my categorical moderator. sim_slopes() knows this and produces simple slopes for each level of the factor moderator.

However, the **order** of the output is not the same as my factor order. For example, if I use a factor variable of sex:
```
factor(Sex, levels=c(1,2), labels=c("Male", "Female")))
```
My order is Male then Female. But the output of sim_slopes() has the order of the factor labels as alphabetical. 

While not a *huge* deal, it can make interpretations prone to error---as the order expectation from the factor function is not followed in the output. Is it possible to have the output of sim_slopes() respect the order of the factor moderator?

**Comment by jacob-long** [comment]
So I believe what's happening here is not that it outputs alphabetically (in my testing), it is *reversing* the order of the factor. This is a funny carryover behavior from `interact_plot()` because the vertical legends in `ggplot2` show factors in reverse order, so in this package I reverse the order of these factors. But that's not needed in `sim_slopes()` of course, it's just the result of shared code. 

I have an update coming out that does not reverse the order of factor moderators and, I think, therefore addresses the behavior you're seeing.

Thanks for the report.
