### ISSUE TITLE
CRAN package for interactions

### ISSUE THREAD

**Issue by Codeboy18989** [jacob-long/interactions#7]
Hello Jacob. When can we expect this package to be on CRAN? Please let me know if you need help with testing. This is what I currently see when I run my code:
![image](https://user-images.githubusercontent.com/4153604/52660954-dc8ed680-2ece-11e9-92ed-66d452589d08.png)

**Comment by jacob-long** [comment]
Thanks for your patience. I submitted to CRAN late last week. Because it is new to CRAN, it requires a human review before it is published. I don't expect any problems, but the timing just depends on the availability of a CRAN volunteer to take a look at it. I would be surprised if it isn't available by the end of the week.

For the time being, you can download the same version from Github by running the following code:

```r
source("https://install-github.me/jacob-long/interactions")
```

**Comment by Codeboy18989** [comment]
Great! Thanks for responding!

**Comment by jacob-long** [comment]
On CRAN now, binary version should be available in the next day or so.
