### ISSUE TITLE
rlang strangeness with sim_slopes

### ISSUE THREAD

**Issue by ClaudiuPapasteri** [jacob-long/interactions#71]
I am not sure if this is a lack of understanding on my part but I haven't been able to succefuly wrap `sim_slopes` within a function. I tried multiple approaches but what works for `interact_plot` doesn't for `sim_slopes` . I posted this [question on SO](https://stackoverflow.com/questions/76065839/rlang-tidy-eval-with-model-formula) and no answer. 

``` r
library(interactions) 
library(rlang)

run_interac_1 <- function(data, out, pred, mod) {
  
  out <- enquo(out)
  pred <- enquo(pred)   
  mod <- enquo(mod)    
  
  model_formula <- paste0(quo_name(out), " ~ ", quo_name(mod), " * ", quo_name(pred))
  model_fit <- lm(formula = model_formula, data = data)
  
  plot <- interactions::interact_plot(model = model_fit,
                                      pred = !!pred, modx = !!mod)
  plot
}

# Runs as expected
run_interac_1(data = mtcars, out = mpg, pred = hp, mod = wt)
```

![](https://i.imgur.com/pge83vo.png)

<sup>Created on 2023-05-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
library(interactions)
library(rlang)

run_interac_2 <- function(data, out, pred, mod) {
  
  out <- enquo(out)
  pred <- enquo(pred)   
  mod <- enquo(mod)    
  
  model_formula <- paste0(quo_name(out), " ~ ", quo_name(mod), " * ", quo_name(pred))
  model_fit <- lm(formula = model_formula, data = data)
  
  simple_slopes <- interactions::sim_slopes(model = model_fit,
                                            pred = !!pred, modx = !!mod)
  simple_slopes
}

# Gives error
run_interac_2(data = mtcars, out = mpg, pred = hp, mod = wt)
#> Error in stats::model.frame(formula = model_formula, data = dt, drop.unused.levels = TRUE): object 'model_formula' not found
```

<sup>Created on 2023-05-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jacob-long** [comment]
This is a tough one and although you're right that I wasn't (this has since been changed) using idiomatic `rlang` to parse the `pred`/`modx`/`mod2` arguments, that doesn't seem to be the issue here. The main explanation is that `sim_slopes()` re-fits the model that you supply and `interact_plot()` does not do that. Why does that matter? Well, the error is happening when I call `update()` inside `sim_slopes()`. When `update()` tries to fit the model again, it looks for a formula object called `model_formula` and can't find it because it's not in the update environment.

These sorts of problems can make my head spin a good bit but I'm going to put a little more time into figuring out whether I can update the models in a way that is more robust to the possibility that users will be programmatically defining the formula.

**Comment by jacob-long** [comment]
In fact, I can replicate this problem with no involvement of `interactions` or `rlang`:

```r
fun1 <- function(dat) {
  form <- "mpg ~ wt"
  mod <- lm(form, data = dat)
  fun2(mod, dat)
}

fun2 <- function(mod, dat) {
  update(mod, data = dat)
}

fun1(mtcars)
#> Error in eval(mf, parent.frame()) : object 'form' not found
```

When we set the model formula using a variable, update can't find the right environment that contains that object.

**Comment by jacob-long** [comment]
Okay, just pushed a change that I'm satisfied is a "fix" for this. The only change to your code needed to make it run would be to make the formula an actual formula rather than a string (because if you make it a formula, it saves the environment with it).

```r
library(interactions)
library(rlang)

run_interac_2 <- function(data, out, pred, mod) {
  
  out <- enquo(out)
  pred <- enquo(pred)   
  mod <- enquo(mod)    
  
  model_formula <- as.formula(paste0(quo_name(out), " ~ ", quo_name(mod), " * ", quo_name(pred)))
  model_fit <- lm(formula = model_formula, data = data)
  
  simple_slopes <- interactions::sim_slopes(model = model_fit,
                                            pred = !!pred, modx = !!mod)
  simple_slopes
}

# No error!
run_interac_2(data = mtcars, out = mpg, pred = hp, mod = wt)
